config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "items#index"

  resources :items
  patch "/items/:id/complete", to: "items#update_complete", as: "complete_item"
  post "/test", to: "items#test"

  # get "/products", to: "products#index"
  # get "products/:id", to: "products#show"
  resources :products

  # same as adding all of these:
  # get "/products", to: "products#index"

  # get "products/new", to: "products#new"
  # post "/products", to: "products#create"

  # get "products/:id", to: "products#show"

  # get "/products/:id/edit", to: "products#edit"
  # patch "products/:id", to: "products#update"
  # put "products/:id", to: "products#update"

  # delete "products/:id", to: "products#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = params[:show_complete].present? ? Item.all : Item.where(complete: true)
    # @items = Item.all
    puts @items

    render :index
  end

  def test
    render html: "<turbo-frame id='test'><p>This is a test element</p></turbo-frame>".html_safe
  end

  def new
    @item = Item.new name: "My Item"
  end

  def create
    @item = Item.new item_params

    if @item.save
      redirect_to @item
    else
      render :new, status: unprocessable_entity
    end
  end

  def show
    @item = Item.find params[:id]
  end

  def edit
    @item = Item.find params[:id]
  end

  def update
    @item = Item.find params[:id]

    if @item.update item_params
      redirect_to @item
    else
      render :edit, status: unprocessable_entity
    end
  end

  def update_complete
    @item = Item.find params[:id]
    @item.update(params.expect(item: [ :complete ]))

    # this works because the request is coming from within a turbo frame, and so it gets replaced
    render partial: "items/item_status", locals: { item: @item }, content_type: "text/html" # force content type because sometimes server sends it back as turbo stream which makes it get appended after the body tag

    # to use other parts of the dom, this would have to be used (items-list is the ID of the element being used)
    # respond_to do |format|
    #   format.turbo_stream do
    #     render turbo_stream: turbo_stream.append("items-list", partial: "items/item", locals: { item: @item })
    #   end
    # end
  end

  def destroy
    @item = Item.find params[:id]
    @item.destroy
    redirect_to items_path
  end

  private
    def item_params
      params.expect item: %i[ name description complete ]
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    
    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.expect(product: [ :name ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/items/_form.html.erb
<%= form_with model: item do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :description %>
        <%= form.text_field :description %>
    </div>

    <div>
        <%= form.label :complete %>
        <%= form.checkbox :complete %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/items/_item.html.erb
<p><%= item.name %></p>
<%= render "items/item_status", item: item %>
<%= link_to "View", item_path(item), data: { turbo_frame: "_top" } %>

app/views/items/_item_status.erb
<%= turbo_frame_tag dom_id(item) do %>
    <%= form_with model: item, url: complete_item_path(item) do |f| %>
        <%= f.check_box :complete, id: "item_#{item.id}_complete", onchange: "this.form.requestSubmit()" %>
        <%= f.label :complete, item.complete ? "Complete" : "Incomplete", for: "item_#{item.id}_complete" %>
    <% end %>
<% end %>

app/views/items/_items.html.erb
<% @items.each do |item| %>
    <%= render item %>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render "form", item: @item %>

app/views/items/index.html.erb
<h1>Todo List</h1>
<%= link_to "New Item", new_item_path %>

<%= form_with url: items_path, method: :get, data: { turbo_frame: "items-list" } do |f| %>
    <%= check_box_tag :show_complete, "1", params[:show_complete].present?, onchange: "this.form.requestSubmit()" %>
    <%= f.label :show_complete %>
<% end %>

<br>

<%= turbo_frame_tag "test" do %>
    
<% end %>

<%= button_to "Click me", "/test", method: :post, data: { turbo_frame: "test" } %>

<br>

<%= turbo_frame_tag "items-list" do %>
    <%= render @items %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render "form", item: @item %>
<%= link_to "Cancel", items_path %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<p><%= @item.description || "No description." %></p>

<%= render "items/item_status", item: @item %>

<%= link_to "Back", items_path %>
<%= link_to "Edit", edit_item_path %>
<%= button_to "Delete", @item, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Test" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>
<%= link_to "Cancel", @product %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to "New Product", new_product_path %>

<div id="products">
    <% @products.each do |product| %>
        <div>
            <%= link_to product.name, product_path(product) %>
        </div>
    <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>
<%= link_to "Cancel", products_path %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<%= link_to "Back", products_path %>
<%= link_to "Edit", edit_product_path %>
<%= button_to "Delete", @product, method: :delete, data: { turbo_confirm: "Are you sure?" } %>